name:                monomer-hagrid
version:             0.0.1.0
synopsis:            A datagrid widget for the Monomer library.
description:         A configurable Monomer widget that shows a scrollable grid of data.
github:              Dretch/monomer-hagrid
homepage:            https://github.com/Dretch/monomer-hagrid#readme
bug-reports:         https://github.com/Dretch/monomer-hagrid/issues
license:             WTFPL
category:            GUI
maintainer:          garethdanielsmith@gmail.com

dependencies:
- base >= 4.7 && < 5
- containers
- data-default-class
- ilist
- lens
- monomer
- text

library:
  source-dirs: src
  default-extensions:
    - DisambiguateRecordFields
    - DuplicateRecordFields
    - OverloadedRecordDot
    - OverloadedStrings
  ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
  generated-other-modules: Paths_monomer_hagrid

executables:
  examples:
    main: Main.hs
    source-dirs: examples
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
    default-extensions:
      - DisambiguateRecordFields
      - DuplicateRecordFields
      - OverloadedRecordDot
      - OverloadedStrings
    dependencies:
      - monomer-hagrid
      - time

tests:
  spec:
    defaults: hspec/hspec@master
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
    default-extensions:
      - DisambiguateRecordFields
      - DuplicateRecordFields
      - OverloadedRecordDot
      - OverloadedStrings
    dependencies:
      - bytestring
      - data-default
      - monomer-hagrid
      - mtl
      - stm