name:                monomer-hagrid
version:             0.3.0.1
synopsis:            A datagrid widget for the Monomer library.
description:         A configurable Monomer widget that shows a scrollable grid of data.
github:              Dretch/monomer-hagrid
homepage:            https://github.com/Dretch/monomer-hagrid#readme
bug-reports:         https://github.com/Dretch/monomer-hagrid/issues
license:             MIT
category:            GUI
maintainer:          garethdanielsmith@gmail.com

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- containers
- data-default-class
- ilist
- lens
- monomer >= 1.5.1.0 && < 1.6
- text

default-extensions:
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - EmptyCase
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - NamedFieldPuns
  - NoFieldSelectors
  - NumericUnderscores
  - OverloadedRecordDot
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables

flags:
  examples:
    description: Whether to build the example executables. Off by default because they are not usually wanted.
    manual: true
    default: false

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

library:
  source-dirs: src
  generated-other-modules: Paths_monomer_hagrid

executables:
  example-basic:
    source-dirs: example-basic
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - monomer-hagrid
      - time
    when:
      - condition: flag(examples)
        then:
          buildable: true
        else:
          buildable: false
  example-big-grid:
    source-dirs: example-big-grid
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - monomer-hagrid
    when:
      - condition: flag(examples)
        then:
          buildable: true
        else:
          buildable: false
  example-resizing-cells:
    source-dirs: example-resizing-cells
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - monomer-hagrid
      - random
    when:
      - condition: flag(examples)
        then:
          buildable: true
        else:
          buildable: false

tests:
  spec:
    defaults: hspec/hspec@master
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - bytestring
      - data-default
      - monomer-hagrid
      - mtl
      - stm