name:                hagrid
version:             0.0.1.0
license:             WTFPL

dependencies:
- base >= 4.7 && < 5
- containers
- data-default-class
- extra
- ilist
- lens
- monomer
- text

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
  ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

executables:
  examples:
    main: Main.hs
    source-dirs: examples
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
    default-extensions:
      - OverloadedStrings
    dependencies:
      - hagrid
      - time
