name:                monomer-hagrid
version:             0.0.1.0
license:             WTFPL

dependencies:
- base >= 4.7 && < 5
- containers
- data-default-class
- ilist
- lens
- monomer
- text

library:
  source-dirs: src
  default-extensions:
    - DisambiguateRecordFields
    - DuplicateRecordFields
    - OverloadedRecordDot
    - OverloadedStrings
  ghc-options: -O2 -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

executables:
  examples:
    main: Main.hs
    source-dirs: examples
    ghc-options: -O2 -threaded -rtsopts -with-rtsopts=-N -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
    default-extensions:
      - DisambiguateRecordFields
      - DuplicateRecordFields
      - OverloadedRecordDot
      - OverloadedStrings
    dependencies:
      - monomer-hagrid
      - time

tests:
  spec:
    defaults: hspec/hspec@master
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
    default-extensions:
      - DisambiguateRecordFields
      - DuplicateRecordFields
      - OverloadedRecordDot
      - OverloadedStrings
    dependencies:
      - bytestring
      - data-default
      - monomer-hagrid
      - mtl
      - stm