name:                monomer-hagrid
version:             0.2.1.0
synopsis:            A datagrid widget for the Monomer library.
description:         A configurable Monomer widget that shows a scrollable grid of data.
github:              Dretch/monomer-hagrid
homepage:            https://github.com/Dretch/monomer-hagrid#readme
bug-reports:         https://github.com/Dretch/monomer-hagrid/issues
license:             MIT
category:            GUI
maintainer:          garethdanielsmith@gmail.com

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- containers
- data-default-class
- ilist
- lens
- monomer >= 1.5.1.0 && < 1.6
- text

default-extensions:
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - FlexibleContexts
  - OverloadedRecordDot
  - OverloadedStrings

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints

library:
  source-dirs: src
  generated-other-modules: Paths_monomer_hagrid

executables:
  example-basic:
    source-dirs: example-basic
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - monomer-hagrid
      - time
  example-big-grid:
    source-dirs: example-big-grid
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - monomer-hagrid
  example-resizing-cells:
    source-dirs: example-resizing-cells
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - monomer-hagrid
      - random

tests:
  spec:
    defaults: hspec/hspec@master
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - bytestring
      - data-default
      - monomer-hagrid
      - mtl
      - stm