name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

    - name: 'Install OS-level packages needed for Monomer'
      run: sudo apt-get update && sudo apt-get install --assume-yes libsdl2-dev libglew-dev

    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        key: stack
        path: ~/.stack
    
    - name: 'Install Stack'
      uses: haskell-actions/setup@v2
      with:
        stack-setup-ghc: true
        enable-stack: true
    
    - name: 'Check formatting'
      uses: mrkkrp/ormolu-action@v14

    - name: 'Check package metadata'
      run: cabal check

    - name: 'Build and test'
      run: stack test

    - name: 'Generate package'
      run: stack sdist

    - name: 'Archive package'
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: .stack-work/dist/*/*/monomer-hagrid-*.tar.gz
        if-no-files-found: error

  publish:

    needs: [build]

    if: github.ref_type == 'tag'

    runs-on: ubuntu-22.04

    environment:
      name: hackage
      url: https://hackage.haskell.org/package/monomer-hagrid

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: package

    - name: 'Publish Package to Hackage'
      run: cabal upload -u "$HACKAGE_USERNAME" -p "$HACKAGE_PASSWORD" --publish */*/*.tar.gz
      env:
        HACKAGE_USERNAME: ${{ secrets.HACKAGE_USERNAME }}
        HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
